FROM mcr.microsoft.com/devcontainers/go:1.25-bookworm

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends postgresql-client

RUN go install github.com/go-delve/delve/cmd/dlv@latest